/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace NexusChainMarketplace {
  export type SubscriptionTierStruct = {
    name: string;
    pricePerMonth: BigNumberish;
    callsPerMonth: BigNumberish;
    features: string[];
    isActive: boolean;
  };

  export type SubscriptionTierStructOutput = [
    name: string,
    pricePerMonth: bigint,
    callsPerMonth: bigint,
    features: string[],
    isActive: boolean
  ] & {
    name: string;
    pricePerMonth: bigint;
    callsPerMonth: bigint;
    features: string[];
    isActive: boolean;
  };

  export type AgentStruct = {
    id: string;
    name: string;
    description: string;
    owner: AddressLike;
    pricePerCall: BigNumberish;
    ratingSum: BigNumberish;
    ratingCount: BigNumberish;
    isActive: boolean;
    ipfsCid: string;
    capabilities: string[];
    subscriptionTiers: NexusChainMarketplace.SubscriptionTierStruct[];
    version: string;
  };

  export type AgentStructOutput = [
    id: string,
    name: string,
    description: string,
    owner: string,
    pricePerCall: bigint,
    ratingSum: bigint,
    ratingCount: bigint,
    isActive: boolean,
    ipfsCid: string,
    capabilities: string[],
    subscriptionTiers: NexusChainMarketplace.SubscriptionTierStructOutput[],
    version: string
  ] & {
    id: string;
    name: string;
    description: string;
    owner: string;
    pricePerCall: bigint;
    ratingSum: bigint;
    ratingCount: bigint;
    isActive: boolean;
    ipfsCid: string;
    capabilities: string[];
    subscriptionTiers: NexusChainMarketplace.SubscriptionTierStructOutput[];
    version: string;
  };
}

export interface NexusChainMarketplaceInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "QUORUM"
      | "VOTE_DURATION"
      | "agentRevenue"
      | "agents"
      | "createProposal"
      | "executeProposal"
      | "getAgent"
      | "getAverageRating"
      | "getSubscriptionTiers"
      | "governanceToken"
      | "listAgent"
      | "listings"
      | "proposals"
      | "purchaseAgent"
      | "rateAgent"
      | "registerAgent"
      | "setTreasury"
      | "treasury"
      | "updateAgent"
      | "updateSubscriptionTiers"
      | "upgradeAgent"
      | "vote"
      | "voterStake"
      | "withdrawTreasury"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentDeactivated"
      | "AgentListed"
      | "AgentPurchased"
      | "AgentRated"
      | "AgentRegistered"
      | "AgentUpgraded"
      | "ProposalCreated"
      | "ProposalExecuted"
      | "VoteCast"
  ): EventFragment;

  encodeFunctionData(functionFragment: "QUORUM", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "VOTE_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "agentRevenue",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "agents", values: [string]): string;
  encodeFunctionData(
    functionFragment: "createProposal",
    values: [string, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "executeProposal",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "getAgent", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getAverageRating",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getSubscriptionTiers",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "governanceToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "listAgent",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "listings", values: [string]): string;
  encodeFunctionData(functionFragment: "proposals", values: [string]): string;
  encodeFunctionData(
    functionFragment: "purchaseAgent",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "rateAgent",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerAgent",
    values: [
      string,
      string,
      string,
      BigNumberish,
      string,
      string[],
      NexusChainMarketplace.SubscriptionTierStruct[],
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setTreasury",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateAgent",
    values: [string, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "updateSubscriptionTiers",
    values: [string, NexusChainMarketplace.SubscriptionTierStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeAgent",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "vote",
    values: [string, boolean, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "voterStake",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawTreasury",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "QUORUM", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "VOTE_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "agentRevenue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "agents", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAgent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAverageRating",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSubscriptionTiers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "governanceToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "listAgent", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "listings", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "proposals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "purchaseAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rateAgent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateSubscriptionTiers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vote", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "voterStake", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawTreasury",
    data: BytesLike
  ): Result;
}

export namespace AgentDeactivatedEvent {
  export type InputTuple = [agentId: string];
  export type OutputTuple = [agentId: string];
  export interface OutputObject {
    agentId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentListedEvent {
  export type InputTuple = [agentId: string, price: BigNumberish];
  export type OutputTuple = [agentId: string, price: bigint];
  export interface OutputObject {
    agentId: string;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentPurchasedEvent {
  export type InputTuple = [
    agentId: string,
    buyer: AddressLike,
    price: BigNumberish,
    seller: AddressLike
  ];
  export type OutputTuple = [
    agentId: string,
    buyer: string,
    price: bigint,
    seller: string
  ];
  export interface OutputObject {
    agentId: string;
    buyer: string;
    price: bigint;
    seller: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentRatedEvent {
  export type InputTuple = [
    agentId: string,
    rating: BigNumberish,
    rater: AddressLike
  ];
  export type OutputTuple = [agentId: string, rating: bigint, rater: string];
  export interface OutputObject {
    agentId: string;
    rating: bigint;
    rater: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentRegisteredEvent {
  export type InputTuple = [
    id: string,
    name: string,
    owner: AddressLike,
    price: BigNumberish
  ];
  export type OutputTuple = [
    id: string,
    name: string,
    owner: string,
    price: bigint
  ];
  export interface OutputObject {
    id: string;
    name: string;
    owner: string;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentUpgradedEvent {
  export type InputTuple = [
    id: string,
    fromVersion: string,
    toVersion: string,
    ipfsCid: string
  ];
  export type OutputTuple = [
    id: string,
    fromVersion: string,
    toVersion: string,
    ipfsCid: string
  ];
  export interface OutputObject {
    id: string;
    fromVersion: string;
    toVersion: string;
    ipfsCid: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalCreatedEvent {
  export type InputTuple = [id: string, title: string, deadline: BigNumberish];
  export type OutputTuple = [id: string, title: string, deadline: bigint];
  export interface OutputObject {
    id: string;
    title: string;
    deadline: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalExecutedEvent {
  export type InputTuple = [proposalId: string, passed: boolean];
  export type OutputTuple = [proposalId: string, passed: boolean];
  export interface OutputObject {
    proposalId: string;
    passed: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoteCastEvent {
  export type InputTuple = [
    proposalId: string,
    voter: AddressLike,
    support: boolean,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    proposalId: string,
    voter: string,
    support: boolean,
    amount: bigint
  ];
  export interface OutputObject {
    proposalId: string;
    voter: string;
    support: boolean;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface NexusChainMarketplace extends BaseContract {
  connect(runner?: ContractRunner | null): NexusChainMarketplace;
  waitForDeployment(): Promise<this>;

  interface: NexusChainMarketplaceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  QUORUM: TypedContractMethod<[], [bigint], "view">;

  VOTE_DURATION: TypedContractMethod<[], [bigint], "view">;

  agentRevenue: TypedContractMethod<[arg0: string], [bigint], "view">;

  agents: TypedContractMethod<
    [arg0: string],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        boolean,
        string,
        string
      ] & {
        id: string;
        name: string;
        description: string;
        owner: string;
        pricePerCall: bigint;
        ratingSum: bigint;
        ratingCount: bigint;
        isActive: boolean;
        ipfsCid: string;
        version: string;
      }
    ],
    "view"
  >;

  createProposal: TypedContractMethod<
    [
      id: string,
      title: string,
      description: string,
      durationDays: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  executeProposal: TypedContractMethod<
    [proposalId: string],
    [void],
    "nonpayable"
  >;

  getAgent: TypedContractMethod<
    [id: string],
    [NexusChainMarketplace.AgentStructOutput],
    "view"
  >;

  getAverageRating: TypedContractMethod<[agentId: string], [bigint], "view">;

  getSubscriptionTiers: TypedContractMethod<
    [id: string],
    [NexusChainMarketplace.SubscriptionTierStructOutput[]],
    "view"
  >;

  governanceToken: TypedContractMethod<[], [string], "view">;

  listAgent: TypedContractMethod<
    [agentId: string, price: BigNumberish],
    [void],
    "nonpayable"
  >;

  listings: TypedContractMethod<
    [arg0: string],
    [
      [string, bigint, bigint, boolean] & {
        agentId: string;
        price: bigint;
        views: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  proposals: TypedContractMethod<
    [arg0: string],
    [
      [string, string, string, bigint, bigint, bigint, boolean, boolean] & {
        id: string;
        title: string;
        description: string;
        forVotes: bigint;
        againstVotes: bigint;
        deadline: bigint;
        executed: boolean;
        exists: boolean;
      }
    ],
    "view"
  >;

  purchaseAgent: TypedContractMethod<[agentId: string], [void], "payable">;

  rateAgent: TypedContractMethod<
    [agentId: string, rating: BigNumberish],
    [void],
    "nonpayable"
  >;

  registerAgent: TypedContractMethod<
    [
      id: string,
      name: string,
      description: string,
      pricePerCall: BigNumberish,
      ipfsCid: string,
      capabilities: string[],
      subscriptionTiers: NexusChainMarketplace.SubscriptionTierStruct[],
      version: string
    ],
    [void],
    "nonpayable"
  >;

  setTreasury: TypedContractMethod<
    [newTreasury: AddressLike],
    [void],
    "nonpayable"
  >;

  treasury: TypedContractMethod<[], [string], "view">;

  updateAgent: TypedContractMethod<
    [id: string, newPrice: BigNumberish, deactivate: boolean],
    [void],
    "nonpayable"
  >;

  updateSubscriptionTiers: TypedContractMethod<
    [id: string, tiers: NexusChainMarketplace.SubscriptionTierStruct[]],
    [void],
    "nonpayable"
  >;

  upgradeAgent: TypedContractMethod<
    [id: string, newVersion: string, newIpfsCid: string],
    [void],
    "nonpayable"
  >;

  vote: TypedContractMethod<
    [proposalId: string, support: boolean, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  voterStake: TypedContractMethod<
    [arg0: AddressLike, arg1: string],
    [bigint],
    "view"
  >;

  withdrawTreasury: TypedContractMethod<
    [recipient: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "QUORUM"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "VOTE_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "agentRevenue"
  ): TypedContractMethod<[arg0: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "agents"
  ): TypedContractMethod<
    [arg0: string],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        boolean,
        string,
        string
      ] & {
        id: string;
        name: string;
        description: string;
        owner: string;
        pricePerCall: bigint;
        ratingSum: bigint;
        ratingCount: bigint;
        isActive: boolean;
        ipfsCid: string;
        version: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "createProposal"
  ): TypedContractMethod<
    [
      id: string,
      title: string,
      description: string,
      durationDays: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "executeProposal"
  ): TypedContractMethod<[proposalId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAgent"
  ): TypedContractMethod<
    [id: string],
    [NexusChainMarketplace.AgentStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAverageRating"
  ): TypedContractMethod<[agentId: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSubscriptionTiers"
  ): TypedContractMethod<
    [id: string],
    [NexusChainMarketplace.SubscriptionTierStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "governanceToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "listAgent"
  ): TypedContractMethod<
    [agentId: string, price: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "listings"
  ): TypedContractMethod<
    [arg0: string],
    [
      [string, bigint, bigint, boolean] & {
        agentId: string;
        price: bigint;
        views: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "proposals"
  ): TypedContractMethod<
    [arg0: string],
    [
      [string, string, string, bigint, bigint, bigint, boolean, boolean] & {
        id: string;
        title: string;
        description: string;
        forVotes: bigint;
        againstVotes: bigint;
        deadline: bigint;
        executed: boolean;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "purchaseAgent"
  ): TypedContractMethod<[agentId: string], [void], "payable">;
  getFunction(
    nameOrSignature: "rateAgent"
  ): TypedContractMethod<
    [agentId: string, rating: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerAgent"
  ): TypedContractMethod<
    [
      id: string,
      name: string,
      description: string,
      pricePerCall: BigNumberish,
      ipfsCid: string,
      capabilities: string[],
      subscriptionTiers: NexusChainMarketplace.SubscriptionTierStruct[],
      version: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTreasury"
  ): TypedContractMethod<[newTreasury: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "updateAgent"
  ): TypedContractMethod<
    [id: string, newPrice: BigNumberish, deactivate: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateSubscriptionTiers"
  ): TypedContractMethod<
    [id: string, tiers: NexusChainMarketplace.SubscriptionTierStruct[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "upgradeAgent"
  ): TypedContractMethod<
    [id: string, newVersion: string, newIpfsCid: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "vote"
  ): TypedContractMethod<
    [proposalId: string, support: boolean, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "voterStake"
  ): TypedContractMethod<[arg0: AddressLike, arg1: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "withdrawTreasury"
  ): TypedContractMethod<[recipient: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "AgentDeactivated"
  ): TypedContractEvent<
    AgentDeactivatedEvent.InputTuple,
    AgentDeactivatedEvent.OutputTuple,
    AgentDeactivatedEvent.OutputObject
  >;
  getEvent(
    key: "AgentListed"
  ): TypedContractEvent<
    AgentListedEvent.InputTuple,
    AgentListedEvent.OutputTuple,
    AgentListedEvent.OutputObject
  >;
  getEvent(
    key: "AgentPurchased"
  ): TypedContractEvent<
    AgentPurchasedEvent.InputTuple,
    AgentPurchasedEvent.OutputTuple,
    AgentPurchasedEvent.OutputObject
  >;
  getEvent(
    key: "AgentRated"
  ): TypedContractEvent<
    AgentRatedEvent.InputTuple,
    AgentRatedEvent.OutputTuple,
    AgentRatedEvent.OutputObject
  >;
  getEvent(
    key: "AgentRegistered"
  ): TypedContractEvent<
    AgentRegisteredEvent.InputTuple,
    AgentRegisteredEvent.OutputTuple,
    AgentRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "AgentUpgraded"
  ): TypedContractEvent<
    AgentUpgradedEvent.InputTuple,
    AgentUpgradedEvent.OutputTuple,
    AgentUpgradedEvent.OutputObject
  >;
  getEvent(
    key: "ProposalCreated"
  ): TypedContractEvent<
    ProposalCreatedEvent.InputTuple,
    ProposalCreatedEvent.OutputTuple,
    ProposalCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ProposalExecuted"
  ): TypedContractEvent<
    ProposalExecutedEvent.InputTuple,
    ProposalExecutedEvent.OutputTuple,
    ProposalExecutedEvent.OutputObject
  >;
  getEvent(
    key: "VoteCast"
  ): TypedContractEvent<
    VoteCastEvent.InputTuple,
    VoteCastEvent.OutputTuple,
    VoteCastEvent.OutputObject
  >;

  filters: {
    "AgentDeactivated(string)": TypedContractEvent<
      AgentDeactivatedEvent.InputTuple,
      AgentDeactivatedEvent.OutputTuple,
      AgentDeactivatedEvent.OutputObject
    >;
    AgentDeactivated: TypedContractEvent<
      AgentDeactivatedEvent.InputTuple,
      AgentDeactivatedEvent.OutputTuple,
      AgentDeactivatedEvent.OutputObject
    >;

    "AgentListed(string,uint256)": TypedContractEvent<
      AgentListedEvent.InputTuple,
      AgentListedEvent.OutputTuple,
      AgentListedEvent.OutputObject
    >;
    AgentListed: TypedContractEvent<
      AgentListedEvent.InputTuple,
      AgentListedEvent.OutputTuple,
      AgentListedEvent.OutputObject
    >;

    "AgentPurchased(string,address,uint256,address)": TypedContractEvent<
      AgentPurchasedEvent.InputTuple,
      AgentPurchasedEvent.OutputTuple,
      AgentPurchasedEvent.OutputObject
    >;
    AgentPurchased: TypedContractEvent<
      AgentPurchasedEvent.InputTuple,
      AgentPurchasedEvent.OutputTuple,
      AgentPurchasedEvent.OutputObject
    >;

    "AgentRated(string,uint8,address)": TypedContractEvent<
      AgentRatedEvent.InputTuple,
      AgentRatedEvent.OutputTuple,
      AgentRatedEvent.OutputObject
    >;
    AgentRated: TypedContractEvent<
      AgentRatedEvent.InputTuple,
      AgentRatedEvent.OutputTuple,
      AgentRatedEvent.OutputObject
    >;

    "AgentRegistered(string,string,address,uint256)": TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;
    AgentRegistered: TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;

    "AgentUpgraded(string,string,string,string)": TypedContractEvent<
      AgentUpgradedEvent.InputTuple,
      AgentUpgradedEvent.OutputTuple,
      AgentUpgradedEvent.OutputObject
    >;
    AgentUpgraded: TypedContractEvent<
      AgentUpgradedEvent.InputTuple,
      AgentUpgradedEvent.OutputTuple,
      AgentUpgradedEvent.OutputObject
    >;

    "ProposalCreated(string,string,uint256)": TypedContractEvent<
      ProposalCreatedEvent.InputTuple,
      ProposalCreatedEvent.OutputTuple,
      ProposalCreatedEvent.OutputObject
    >;
    ProposalCreated: TypedContractEvent<
      ProposalCreatedEvent.InputTuple,
      ProposalCreatedEvent.OutputTuple,
      ProposalCreatedEvent.OutputObject
    >;

    "ProposalExecuted(string,bool)": TypedContractEvent<
      ProposalExecutedEvent.InputTuple,
      ProposalExecutedEvent.OutputTuple,
      ProposalExecutedEvent.OutputObject
    >;
    ProposalExecuted: TypedContractEvent<
      ProposalExecutedEvent.InputTuple,
      ProposalExecutedEvent.OutputTuple,
      ProposalExecutedEvent.OutputObject
    >;

    "VoteCast(string,address,bool,uint256)": TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;
    VoteCast: TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;
  };
}
